blueprint:
  name: Circadian Light Hue Dimmer Switch
  description: >
    Control Hue Dimmer Switches via Circadian Light with freeze and broadcast support
  domain: automation
  input:
    switch_device:
      name: Switch Device(s)
      description: The Hue/ZHA switch device(s) to use
      selector:
        device:
          multiple: true
          filter:
            - integration: zha
              manufacturer: Signify Netherlands B.V.
              model: RWL021
            - integration: zha
              manufacturer: Signify Netherlands B.V.
              model: RWL022
            - integration: zha
              manufacturer: Philips
              model: RWL021
            - integration: zha
              manufacturer: Philips
              model: RWL020
            - integration: zha
              manufacturer: Signify Netherlands B.V.
              model: RDM002
            - integration: zha
              manufacturer: Signify Netherlands B.V.
              model: ROM001
            - integration: zha
              manufacturer: Signify Netherlands B.V.
              model: RDM003
            - integration: zha
              manufacturer: Philips
              model: ROM001
            - integration: zha
              manufacturer: Philips
              model: RDM003
            - integration: hue
              manufacturer: Signify Netherlands B.V.
              model: Hue dimmer switch (RWL022)
            - integration: hue
              manufacturer: Signify Netherlands B.V.
              model: Hue dimmer switch (RWL021)
            - integration: hue
              manufacturer: Signify Netherlands B.V.
              model: Hue dimmer switch
    target_areas:
      name: Target Areas
      description: The area(s) to control when buttons are pressed
      selector:
        area:
          multiple: true

mode: restart
max_exceeded: silent

# -- Triggers ------------------------------------------------------------------
trigger:
  # ZHA single-press events
  - platform: event
    event_type: zha_event
    event_data:
      command: "on_press"
    id: zha_on
  - platform: event
    event_type: zha_event
    event_data:
      command: "off_press"
    id: zha_off
  - platform: event
    event_type: zha_event
    event_data:
      command: "up_press"
    id: zha_up
  - platform: event
    event_type: zha_event
    event_data:
      command: "down_press"
    id: zha_down

  # ZHA double-press events
  - platform: event
    event_type: zha_event
    event_data:
      command: "on_double_press"
    id: zha_on_double
  - platform: event
    event_type: zha_event
    event_data:
      command: "off_double_press"
    id: zha_off_double
  - platform: event
    event_type: zha_event
    event_data:
      command: "up_double_press"
    id: zha_up_double
  - platform: event
    event_type: zha_event
    event_data:
      command: "down_double_press"
    id: zha_down_double

  # ZHA triple-press events
  - platform: event
    event_type: zha_event
    event_data:
      command: "on_triple_press"
    id: zha_on_triple
  - platform: event
    event_type: zha_event
    event_data:
      command: "off_triple_press"
    id: zha_off_triple
  - platform: event
    event_type: zha_event
    event_data:
      command: "up_triple_press"
    id: zha_up_triple
  - platform: event
    event_type: zha_event
    event_data:
      command: "down_triple_press"
    id: zha_down_triple

  # ZHA quadruple-press events
  - platform: event
    event_type: zha_event
    event_data:
      command: "on_quadruple_press"
    id: zha_on_quadruple
  - platform: event
    event_type: zha_event
    event_data:
      command: "off_quadruple_press"
    id: zha_off_quadruple
  - platform: event
    event_type: zha_event
    event_data:
      command: "up_quadruple_press"
    id: zha_up_quadruple
  - platform: event
    event_type: zha_event
    event_data:
      command: "down_quadruple_press"
    id: zha_down_quadruple

  # ZHA quintuple-press events
  - platform: event
    event_type: zha_event
    event_data:
      command: "on_quintuple_press"
    id: zha_on_quintuple
  - platform: event
    event_type: zha_event
    event_data:
      command: "off_quintuple_press"
    id: zha_off_quintuple
  - platform: event
    event_type: zha_event
    event_data:
      command: "up_quintuple_press"
    id: zha_up_quintuple
  - platform: event
    event_type: zha_event
    event_data:
      command: "down_quintuple_press"
    id: zha_down_quintuple

  # ZHA hold events (fires repeatedly while held)
  - platform: event
    event_type: zha_event
    event_data:
      command: "on_hold"
    id: zha_on_hold
  - platform: event
    event_type: zha_event
    event_data:
      command: "off_hold"
    id: zha_off_hold
  - platform: event
    event_type: zha_event
    event_data:
      command: "up_hold"
    id: zha_up_hold
  - platform: event
    event_type: zha_event
    event_data:
      command: "down_hold"
    id: zha_down_hold

  # Hue Bridge single-press (subtype: 1=ON, 2=UP, 3=DOWN, 4=OFF)
  - platform: event
    event_type: hue_event
    event_data:
      type: short_release
      subtype: 1
    id: hue_on
  - platform: event
    event_type: hue_event
    event_data:
      type: short_release
      subtype: 4
    id: hue_off
  - platform: event
    event_type: hue_event
    event_data:
      type: short_release
      subtype: 2
    id: hue_up
  - platform: event
    event_type: hue_event
    event_data:
      type: short_release
      subtype: 3
    id: hue_down

# -- Variables -----------------------------------------------------------------
variables:
  areas: !input target_areas
  switches: !input switch_device
  area_targets: "{{ areas if areas is iterable and areas is not string else [areas] }}"
  first_area: "{{ area_targets[0] if area_targets else none }}"

# -- Actions -------------------------------------------------------------------
# Button mapping:
#   on-off: 1x toggle, 2x glo_up (send to zone), 3x freeze, 4x-5x reserved, hold RESERVED
#   up:     1x step_up, 2x color_up, 3x britelite, 4x-5x reserved, hold bright_up
#   down:   1x step_down, 2x color_down, 3x nitelite, 4x-5x reserved, hold bright_down
#   hue:    1x [cycle scope], 2x glo_down (reset area), 3x glo_reset (reset zone), 4x-5x reserved, hold RESERVED
action:
  # Only proceed if the event came from one of our configured devices
  - condition: template
    value_template: >
      {% set ds = switches if switches is iterable else [switches] %}
      {{ trigger.event.data.device_id in ds }}

  - choose:
      # ========================================================================
      # POWER BUTTON (on-off)
      # 1x: toggle, 2x: broadcast, 3x-5x: reserved, hold: RESERVED
      # ========================================================================

      # Power 1x -> circadian_toggle
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: zha_on
              - condition: trigger
                id: hue_on
        sequence:
          - service: circadian.circadian_toggle
            data:
              area_id: "{{ area_targets }}"

      # Power 2x -> glo_up (push area state to zone, propagate to all areas)
      - conditions:
          - condition: trigger
            id: zha_on_double
        sequence:
          - service: circadian.glo_up
            data:
              area_id: "{{ first_area }}"

      # Power 3x -> freeze_toggle
      - conditions:
          - condition: trigger
            id: zha_on_triple
        sequence:
          - service: circadian.freeze_toggle
            data:
              area_id: "{{ area_targets }}"

      # Power 4x -> reserved
      # Power 5x -> reserved
      # Power hold -> RESERVED for magic button

      # ========================================================================
      # UP (BRIGHTER) BUTTON
      # 1x: step_up, 2x: color_up, 3x: britelite, 4x-5x: reserved, hold: bright_up
      # ========================================================================

      # Up 1x -> step_up
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: zha_up
              - condition: trigger
                id: hue_up
        sequence:
          - service: circadian.step_up
            data:
              area_id: "{{ area_targets }}"

      # Up 2x -> color_up
      - conditions:
          - condition: trigger
            id: zha_up_double
        sequence:
          - service: circadian.color_up
            data:
              area_id: "{{ area_targets }}"

      # Up 3x -> britelite preset
      - conditions:
          - condition: trigger
            id: zha_up_triple
        sequence:
          - service: circadian.set
            data:
              area_id: "{{ area_targets }}"
              preset: britelite
              enable: true

      # Up 4x -> reserved
      # Up 5x -> reserved

      # Up hold -> bright_up
      - conditions:
          - condition: trigger
            id: zha_up_hold
        sequence:
          - service: circadian.bright_up
            data:
              area_id: "{{ area_targets }}"

      # ========================================================================
      # DOWN (DIMMER) BUTTON
      # 1x: step_down, 2x: color_down, 3x: nitelite, 4x-5x: reserved, hold: bright_down
      # ========================================================================

      # Down 1x -> step_down
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: zha_down
              - condition: trigger
                id: hue_down
        sequence:
          - service: circadian.step_down
            data:
              area_id: "{{ area_targets }}"

      # Down 2x -> color_down
      - conditions:
          - condition: trigger
            id: zha_down_double
        sequence:
          - service: circadian.color_down
            data:
              area_id: "{{ area_targets }}"

      # Down 3x -> nitelite preset
      - conditions:
          - condition: trigger
            id: zha_down_triple
        sequence:
          - service: circadian.set
            data:
              area_id: "{{ area_targets }}"
              preset: nitelite
              enable: true

      # Down 4x -> reserved
      # Down 5x -> reserved

      # Down hold -> bright_down
      - conditions:
          - condition: trigger
            id: zha_down_hold
        sequence:
          - service: circadian.bright_down
            data:
              area_id: "{{ area_targets }}"

      # ========================================================================
      # HUE BUTTON (off)
      # 1x: [cycle scope], 2x: reset (area), 3x: glo_reset (zone), 4x-5x: reserved, hold: RESERVED
      # ========================================================================

      # Hue 1x -> [coming soon: cycle Scope]
      # - conditions:
      #     - condition: or
      #       conditions:
      #         - condition: trigger
      #           id: zha_off
      #         - condition: trigger
      #           id: hue_off
      #   sequence:
      #     - service: circadian.cycle_scope
      #       data:
      #         area_id: "{{ area_targets }}"

      # Hue 2x -> glo_down (reset area - pull zone state to this area)
      - conditions:
          - condition: trigger
            id: zha_off_double
        sequence:
          - service: circadian.glo_down
            data:
              area_id: "{{ first_area }}"

      # Hue 3x -> glo_reset (reset zone and all member areas)
      - conditions:
          - condition: trigger
            id: zha_off_triple
        sequence:
          - service: circadian.glo_reset
            data:
              area_id: "{{ first_area }}"

      # Hue 4x -> reserved
      # Hue 5x -> [coming soon: Sleep]
      # Hue hold -> RESERVED for magic button
